version: '3'
services:
  nuxt.js:
    container_name: nuxt.js
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./src:/src:cached
      # exclude volumes
      - /src/app/node_modules
    tty: true
    stdin_open: true
    # Hot Module Replacement (HMR) is enable for virtual box.
    environment:
      - CHOKIDAR_USEPOLLING=true